#数据源配置
datasource:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/test
  username: root
  password:
  minConn: 3
  maxConn: 150
  timeout: 2000 #数据库连接超时时间，单位（毫秒）
#服务启动配置
server:
  port: 9001
  showSQL: true
  sessionTimeout: 1800000 #session过期时间，单位（毫秒）
  fileTmp: /home/zhukai/tmp #文件上传下载目录